"""init_schema

Revision ID: 84c1aa6d333a
Revises: None
Create Date: 2022-07-05 00:44:36.813202

"""

# revision identifiers, used by Alembic.
revision = '84c1aa6d333a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=15), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('physical_network', sa.String(length=255), nullable=True),
    sa.Column('network_type', sa.String(length=40), nullable=True),
    sa.Column('segmentation_id', sa.Integer(), nullable=True),
    sa.Column('local_vlan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('segmentation_id')
    )
    # ### end Alembic commands ###